export const defaultSermons = [
  {
    id: 1,
    title: "Year of Supernatural Advancement",
    minister: "Pastor Samson Ayangoke",
    date: "2026-01-01",
    bibleText: "1 Samuel 12:6, Deuteronomy 1:12",
    category: "The Supernatural",
    coverPhoto: "https://www.media.hgbcinfluencers.org/sermon_image/2026/year-of-supanatural-advancement.jpeg",
    featureStatus: true,
    audioSource: "https://www.media.hgbcinfluencers.org/audio/2026/january/Year of Supernatural Advancement.mp3",
  },
  {
    id: 2,
    title: "Supernatural Advancement",
    minister: "Pastor Samson Ayangoke",
    date: "2026-01-04",
    bibleText: "1 Samuel 12:6, Deuteronomy 1:12",
    category: "The Supernatural",
    coverPhoto: "https://www.media.hgbcinfluencers.org/sermon_image/2026/supernatural-advancement.jpeg",
    featureStatus: true,
    audioSource: "https://www.media.hgbcinfluencers.org/audio/2026/january/Supernatural Advancement.mp3",
  },
  {
    id: 3,
    title: "Self Control II",
    minister: "Pastor Samson Ayangoke",
    date: "2026-02-01",
    bibleText: "Galatians 5:23",
    category: "Garden of The Spirit",
    coverPhoto: "https://www.media.hgbcinfluencers.org/sermon_image/2026/self-control-ii.jpeg",
    featureStatus: true,
    audioSource: "https://www.media.hgbcinfluencers.org/audio/2026/february/Self_Control_II.mp3",
  },
  {
    id: 4,
    title: "Self Control III",
    minister: "Pastor Samson Ayangoke",
    date: "2026-02-18",
    bibleText: "Proverbs 25:28",
    category: "Garden of The Spirit",
    coverPhoto: "https://www.media.hgbcinfluencers.org/sermon_image/2026/self-control-iii.jpeg",
    featureStatus: true,
    audioSource: "https://www.media.hgbcinfluencers.org/audio/2026/february/Self_Control_III.mp3",
  },
  {
    id: 5,
    title: "Keys to Advancement",
    minister: "Pastor Samson Ayangoke",
    date: "2026-03-01",
    bibleText: "Joshua 1:8",
    category: "The Supernatural",
    coverPhoto: "https://www.media.hgbcinfluencers.org/sermon_image/2026/bible_study.jpeg",
    featureStatus: true,
    audioSource: "https://www.media.hgbcinfluencers.org/audio/2026/march/Keys_to_Advancement.mp3",
  },
  {
    id: 6,
    title: "Sitting at His Feet",
    minister: "Pastor Stephen Bamigbola",
    date: "2026-03-04",
    bibleText: "Luke 10:39",
    category: "Fellowship",
    coverPhoto: "https://www.media.hgbcinfluencers.org/sermon_image/2026/bible_study.jpeg",
    featureStatus: true,
    audioSource: "https://www.media.hgbcinfluencers.org/audio/2026/march/Sitting_at_His_Feet.mp3",
  },
  {
    id: 7,
    title: "Rebuilding Broken Walls I",
    minister: "Pastor Samson Ayangoke",
    date: "2026-03-08",
    bibleText: "Nehemiah 2:17",
    category: "Restoration",
    coverPhoto: "https://www.media.hgbcinfluencers.org/sermon_image/2026/rebuilding-broken-walls-1.jpeg",
    featureStatus: true,
    audioSource: "https://www.media.hgbcinfluencers.org/audio/2026/march/Rebuilding_Broken_Walls_Part_1.mp3",
  },
  {
    id: 8,
    title: "Cultivating His Presence",
    minister: "Pastor Ayanfe Fakunle",
    date: "2026-03-11",
    bibleText: "Psalm 16:11",
    category: "Fellowship",
    coverPhoto: "https://www.media.hgbcinfluencers.org/sermon_image/2026/bible_study.jpeg",
    featureStatus: true,
    audioSource: "https://www.media.hgbcinfluencers.org/audio/2026/march/Cultivating_His_Presence.mp3",
  }
];
